version: "3.7"
services:
  postgres:
    container_name: 'postgres'
    image: 'mdillon/postgis:10'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data  
  pgadmin:
    container_name: 'pg_admin'
    image: dpage/pgadmin4
    ports:
      - '5431:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret

volumes:
  postgres:
